### ISSUE TITLE
Training of Model

### ISSUE THREAD

**Issue by Nikhil041098** [coding-blocks-archives/machine-learning-online-2018#11]
![Capture](https://user-images.githubusercontent.com/70448817/91645169-780b7c00-ea60-11ea-9b80-c3378b6c8735.PNG)

nothing happens after running this cell...
no models were created at the destination folder...it took a sec to run this cell...also there was no error message

**Comment by Nikhil041098** [comment]
![Capture1](https://user-images.githubusercontent.com/70448817/91654459-7a082600-eac6-11ea-87dd-78293eef8e44.PNG)
What is the problem here???

**Comment by mohit2016** [comment]
Check your encoding_train dictionary, is it containing keys like "2513260012_03d33305cf.jpg" or just "2513260012_03d33305cf" without .jpg.
In case .jpg is not there in the keys,  in your line no. 9 remove ".jpg" that you have explicitly written. The correct statement then would be
<b>photo = encoding_train[key]</b>

**Comment by Nikhil041098** [comment]
![Capture2](https://user-images.githubusercontent.com/70448817/91668958-9cce2500-eb2e-11ea-8caf-c1437160b5ba.PNG)
to_categorical not defined???

**Comment by mohit2016** [comment]
Just do a simple google search for these errors. or post on the doubt portal. 
Here, Make sure you have imported to_categorical function from keras using the statement
from keras.utils import to_categorical

**Comment by Nikhil041098** [comment]
Thank u for your reply. Actually i have imported that module but it was in
another cell at the very beginning. I don't know why it wasn't
working...later on i imported that module in the same cell then it
worked...but after that another error is coming...i have sent that you in
this mail...kindly have a look into that...this project is important for me.
Expecting a reply from you soon. And again thank you for your time
